#!/bin/bash
#===================================================================================
#
#         FILE: digitize-dvd
#
#        USAGE: digitize-dvd 
#
#      SUMMARY: Script to digitize my DVD collection and manage the resulting file.
#  DESCRIPTION: This is a lot of glue and automation on top of my other actual 
#               ripping and transcoding functions.  It's been kind of fun designing
#               and figuring out how to do this.
#
#      PROJECT: Media Collection (media-archive)
#      OPTIONS: 
# REQUIREMENTS: dvdbackup
# PACKAGES REQ: dvdbackup
#         BUGS: Probably dozens.
#        NOTES: ---
#       AUTHOR: KlfJoat
#      VERSION: 0.1
#      CREATED: 2014-05-03
#     REVISION: ---
#===================================================================================

################################
####### CHECK CONDITIONS #######
################################
### Check for necessary commands
my_needed_commands="find basename /bin/rm mktemp pwd zenity"
missing_counter=0
for needed_command in $my_needed_commands; do
  if ! hash "$needed_command" >/dev/null 2>&1; then
    printf "Command not found in PATH: %s\n" "$needed_command" >&2
    ((missing_counter++))
  fi
done
if ((missing_counter > 0)); then
  printf "Minimum %d commands are missing in PATH, aborting\n" "$missing_counter" >&2
  exit 1
fi

### Check for enough HDD space.  43GB = 18GB + 25GB buffer
### Check if DVD is a movie or TV show

##############################
####### INITIALIZATION #######
##############################
### Create temp dir
TMPDIR=$(mktemp --quiet --directory --tmpdir=~/tmp) || { echo "Failed to create temp directory."; exit 1; }
olddir=$(pwd)
cd $TMPDIR

### Set up traps for program exit

###########################################
####### DUAL - RIP AND GET DVD INFO #######
###########################################
dvdtoiso

### Figure out ISO filename (should be the only one in our temp directory)
isofile=$(find *.iso)

# Get filename minus dirs and minus ext (use for transcode filename)
basename=$(basename --suffix=.iso $isofile)
transcodefilename="$basename.mkv"

###########################################
#?????? ADD DISC TO TOC SPREADSHEET ???????
###########################################

#########################
####### TRANSCODE #######
#########################

###########################
####### COPY TO NAS #######
###########################
### Check for filename collision
### Copy rip to NAS
### Copy transcode to NAS

###############################################
####### COPY TO EXT HDD OR HOLDING AREA #######
###############################################
### Check for ext HDD
### Check for filename collision
### Copy rip to ext HDD
### Copy transcode to ext HDD

########################
####### CLEAN UP #######
########################
### Change back
cd $olddir
### Delete rip and transcode
#/bin/rm -rf $TMPDIR
